name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: CheckoutCode
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      width:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /httpdocs
          git pull
          npm install
          npm run build
